### ISSUE TITLE
Error handler not working with SP2

### ISSUE THREAD

**Issue by pmminov** [Adobe-Marketing-Cloud/aem-project-archetype#55]
Hi, I just run the project as is and had it working on AEM 6.0.0. After installing SP2 the error handler for missing pages will not fire and it will default to the one from Apache Sling.

This is the cause

Caused by: java.lang.IllegalArgumentException: Argument cannot be null if path is not absolute: resource.js
	at io.sightly.java.api.ResourceResolution.resolveComponent(ResourceResolution.java:101)
	at io.sightly.java.api.ResourceResolution.resolveComponentRelative(ResourceResolution.java:60)
	at io.sightly.js.JsEnvironment.run(JsEnvironment.java:93)
	at io.sightly.js.use.DependencyResolver.resolve(DependencyResolver.java:54)
	at io.sightly.js.use.UseFunction.use(UseFunction.java:78)
	at io.sightly.js.use.UseFunction.call(UseFunction.java:66)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1110)
	at org.apache.sling.scripting.javascript.internal.RhinoJavaScriptEngine.eval(RhinoJavaScriptEngine.java:116)

Any ides as to what si breaking this?

**Comment by rombert** [comment]
Maybe @raducotescu can help here? We have a basic 404.html script at /apps/sling/servlet/errorhandler/404.html which is exactly [404.html from this repo|https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/blob/aa800187eb0d510fb06389eb91914c1c8e8e1f90/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/sling/servlet/errorhandler/404.html].

When I access a non-existing resource I get the default script as well ( 6.0 SP2 ) and the recent requests console confirms that the custom 404.html script is executed but fails:

      2 TIMER_START{handleError:status=404}
      2 TIMER_END{0,handleError:status=404} Using handler /apps/sling/servlet/errorhandler/404.html
      4 LOG SCRIPT ERROR: io.sightly.java.api.SightlyUseException: javax.script.ScriptException: Failure running script /apps/sling/servlet/errorhandler/404.html: Argument cannot be null if path is not absolute: resource.js
      5 TIMER_END{3,handleError:status=404} Error handler finished

I have removed the `data-sly-use` attribute, but that makes no difference.

**Comment by raducotescu** [comment]
Apparently this is a bug in the currently unmaintained {{io.sightly.java.api.ResourceResolution}} class. My suggestion would be to try to install CQ-6.0.0-FEATUREPACK-6431 [0] on your system. This will upgrade the Sightly engine to what was delivered in AEM 6.1, where the bug you've encountered doesn't manifest.

[0] - https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq600/featurepack/cq-6.0.0-featurepack-6431

**Comment by pmminov** [comment]
That fixed it. Worth mentioning on a README or what not. Thank you very much.
