### ISSUE TITLE
Cannot create a project from command line

### ISSUE THREAD

**Issue by ramo102** [Adobe-Marketing-Cloud/aem-project-archetype#99]
Hi,

I'm not able to create a project following the instructions in your README.md.

The command launched in the terminal is:

`mvn -e org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=11 -DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/ -DgroupId=com.example.corporate -DartifactId=ciccio -Dversion=0.0.1-SNAPSHOT -DartifactName="Ciccio Pasticcio"`

Output:

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building AEM Multi-Module Archetype 12-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ aem-project-archetype >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ aem-project-archetype <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ aem-project-archetype ---
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [com.adobe.granite.archetypes:aem-project-archetype:8 -> https://repo.adobe.com/nexus/content/groups/public] found in catalog https://repo.adobe.com/nexus/content/groups/public/
[INFO] Using property: groupId = com.example.corporate
[INFO] Using property: artifactId = ciccio
[INFO] Using property: version = 0.0.1-SNAPSHOT
[INFO] Using property: package = com.example.corporate
Define value for property 'appsFolderName':  ciccio: : 
[INFO] Using property: artifactName = Ciccio Pasticcio
Define value for property 'componentGroupName':  ciccio: : 
Define value for property 'contentFolderName':  ciccio: : 
Define value for property 'cssId':  ciccio: : 
Define value for property 'packageGroup':  ciccio: : 
Define value for property 'siteName':  ciccio: : 
Confirm properties configuration:
groupId: com.example.corporate
artifactId: ciccio
version: 0.0.1-SNAPSHOT
package: com.example.corporate
appsFolderName: ciccio
artifactName: Ciccio Pasticcio
componentGroupName: ciccio
contentFolderName: ciccio
cssId: ciccio
packageGroup: ciccio
siteName: ciccio
 Y: : y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: aem-project-archetype:11
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.example.corporate
[INFO] Parameter: artifactId, Value: ciccio
[INFO] Parameter: version, Value: 0.0.1-SNAPSHOT
[INFO] Parameter: package, Value: com.example.corporate
[INFO] Parameter: packageInPathFormat, Value: com/example/corporate
[INFO] Parameter: artifactName, Value: Ciccio Pasticcio
[INFO] Parameter: componentGroupName, Value: ciccio
[INFO] Parameter: groupId, Value: com.example.corporate
[INFO] Parameter: contentFolderName, Value: ciccio
[INFO] Parameter: siteName, Value: ciccio
[INFO] Parameter: appsFolderName, Value: ciccio
[INFO] Parameter: version, Value: 0.0.1-SNAPSHOT
[INFO] Parameter: cssId, Value: ciccio
[INFO] Parameter: package, Value: com.example.corporate
[INFO] Parameter: packageGroup, Value: ciccio
[INFO] Parameter: artifactId, Value: ciccio
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.698 s
[INFO] Finished at: 2017-08-03T07:02:50+02:00
[INFO] Final Memory: 16M/211M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project aem-project-archetype: org.apache.maven.archetype.exception.InvalidPackaging: Unable to add module to the current project as it is not of packaging type 'pom' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project aem-project-archetype: org.apache.maven.archetype.exception.InvalidPackaging: Unable to add module to the current project as it is not of packaging type 'pom'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: org.apache.maven.archetype.exception.InvalidPackaging: Unable to add module to the current project as it is not of packaging type 'pom'
	at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execute(CreateProjectFromArchetypeMojo.java:195)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I already updated my settings.xml as described [here](https://helpx.adobe.com/experience-manager/using/first-osgi.html).

Environment:

- Arch Linux 4.11.9-1
- java 1.8.0_131
- maven 3.5.0

**Comment by rombert** [comment]
Are you by any change executing this in the git checkout of the aem-project-archetype project? You should do this in a directory without a pom.xml file.

**Comment by ramo102** [comment]
Definitively yes. :)

It works, sorry for the inconvenience.

**Comment by rombert** [comment]
Glad to hear you got it sorted out :-)
